# Generated by Django 6.1.1 on 2026-09-26 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_delivery_date', models.DateField(blank=True, null=True)),
                ('carrier', models.CharField(blank=True, max_length=255)),
                ('pallet_count', models.PositiveIntegerField(blank=True, null=True)),
                ('package_count', models.PositiveIntegerField(blank=True, null=True)),
                ('total_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('loading_metres', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('vehicle_registration', models.CharField(blank=True, max_length=50)),
                ('supplier_comments', models.TextField(blank=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('warehouse_comment', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('changes_requested', 'Changes requested'), ('scheduled', 'Scheduled'), ('received', 'Received'), ('rejected', 'Rejected')], default='draft', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Discrepancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('quantity', 'Quantity'), ('damaged_goods', 'Damaged goods'), ('incorrect_products', 'Incorrect products'), ('pallet_package_count', 'Pallet/package count'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discrepancies', to='inbound.delivery')),
            ],
        ),
        migrations.AddField(
            model_name='delivery',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='inbound.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='inbound.supplier'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='inbound.warehouse'),
        ),
    ]
